### ISSUE TITLE
다크모드 건의

### ISSUE THREAD

**Issue by kff11** [sjegink/sjegink.github.io#1]
제가 눈이 좀 안좋아서 다크모드로 생활하고 있는데
이쪽 웹페이지 키자마자 눈뽕맞고 시력이 낮아졌습니다..

미디어 쿼리중 prefers-color-scheme 이란 속성을 활용하시면 괜찮을 것 같습니다.
해당 속성은 사용자가 지정한 테마 설정 값을 들고옵니다..

@media (prefers-color-scheme: dark) {
   ...
}

**Comment by sjegink** [comment]
Thank you for your interest to my project.

Your request has been accepted and applied.

Do let me know if you have any further concerns or queries and I would be happy to satisfy you further.

Sincerely,
sjegink
